const frenchSurnames = [
  // https://en.wikipedia.org/wiki/French_name
  "DUBOIS","DUPONT","DURAND","MARTIN","BERNARD","PETIT","THOMAS","RICHARD","ROBERT","MOREAU",
  "SIMON","LAURENT","LEROY","GARCIA","DAVID","BERTRAND","ROUX","VINCENT","FERRAND","CLARK",
  "MILLER","GUILLEMET","FABRE","FABIEN","NOËL","RENAUD","ROUSSEAU","LEFÈVRE","MARCHAND","GUÉRIN",
  "BOUCHER","LEBRUN","DUVAL","PERRIN","MORIN","DESCHAMPS","COLIN","CARON","GUILLAUME","MATHIEU",
  "DELAUNAY","GERMAIN","ROYER","LOISEAU","SCHMITT","ROUSSEL","DUPUIS","LECLERC","SANCHEZ","GÉRARD",
]

export default frenchSurnames;
