const frenchNames = {
  0: [
    //https://www.insee.fr/fr/statistiques/3532172
    "ABDALAH","ABDALLAH","ABDE","ABDEL","ABDEL-HAKIM","ABDEL-KADER","ABDEL-KRIM","ABDELAKIM","ABDELALI","ABDELATIF",
    "ABDELHADI","ABDELHAFID","ABDELHAK","ABDELHAKIM","ABDELHALIM","ABDELILAH","ABDELJALIL","ABDELKADER","ABDELKRIM","ABDUL-HADI",
    "ABDELLAH","ABDELLATIF","ABDELLAZIZ","ABDELMADJID","ABDELMAJID","ABDELMALEK","ABDELMOUNAIM","ABDELMOUMEN","ABDELNASSER","ABDELQADER",
    "ABDELQADIR","ABDELRANI","ABDELWAHAB","ABDELWAKIL","ABDI","ABDIKADER","ABDILAHI","ABDOLLAH","ABDOULAYE","ABDOURAHMANE",
    "ABDOURRAHMAN","ABDOURRAHMANE","ABDUL","ABDUL-AZIZ","ABDUL-HALIM","ABDUL-JALIL","ABDUL-KADER","ABDULRAHMAN","ABDULRASHID","ABDULSALAM",
  ],
  1:[
  //https://www.insee.fr/fr/statistiques/3532172
    "ADÈLE","AGNÈS","ALICE","AMÉLIE","ANAÏS","ANDRÉE","ANNA","ANNE","AURÉLIE","BRIGITTE",
    "CAMILLE","CAROLINE","CATHERINE","CHARLOTTE","CHLOÉ","CHRISTINE","CLÉMENCE","CÉCILE","DANIELLE","DOMINIQUE",
    "ELISABETH","EMMA", "ESTELLE", "FLORENCE", "FRANÇOISE", "GAËLLE", "GENEVIÈVE", "HÉLÈNE", "ISABELLE", "JULIE",
    "LAURENCE","LUCIE","MARGUERITE","MARIE","MARTINE","MATHILDE","MONIQUE","NATHALIE","NICOLE","ODILE",
    "OLIVIA","PATRICIA","PAULINE","SABINE","SOPHIE","VALÉRIE","VÉRONIQUE","VIRGINIE","YVONNE","Élodie"
  ]
};

export default frenchNames;
